	local actor = db.actor
-- ==================================================================
-- Покажем сообщение при нажатии на кнопку.
news_manager.send_tip(actor, "Вы нажали на клавишу Scroll Lock.")
-- ==================================================================
-- Восстановим параметры ГГ.
actor.health = 1
actor.radiation = 0
actor.power = 1
-- ==================================================================
-- Пример вызова функции из текущего файла.
function testFunc()
	local function localFunc(_, item)
			actor:drop_item(item)
	end
	actor:iterate_inventory(localFunc, nil)
end
testFunc()
-- ==================================================================